name: Python Application CI/CD

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install -r requirements.txt

      - name: Ejecutar pruebas
        run: pytest

      - name: Ejecutar aplicación
        run: python app.py

      - name: Construir imagen Docker
        run: docker build -t ghcr.io/drewcrx/ejercicio:3.0.0 .

      - name: Publicar imagen
        run: docker push ghcr.io/drewcrx/ejercicio:3.0.0    